"""careflow_daily_analytics -- incremental daily run of the CareFlow pipeline.

Runs the same pipeline as careflow_end_to_end minus synthetic data
generation (never regenerated by default) and the optional dbt snapshot/
docs stages, on a daily schedule. Relies entirely on each stage's own
existing checksum/incremental behavior (Silver, Gold, and the PostgreSQL
warehouse loader all skip unchanged data on a plain, non-forced run;
Bronze always fully reprocesses, per its own design -- see
src/careflow/bronze/ingest.py).
"""

from __future__ import annotations

import sys
from datetime import datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "plugins"))

from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.utils.trigger_rule import TriggerRule

from careflow_callbacks import (
    dag_failure_callback,
    dag_success_callback,
    task_failure_callback,
    task_retry_callback,
    task_success_callback,
)
from careflow_operators import (
    CareFlowCommandOperator,
    build_run_summary,
    get_project_root,
    raise_if_run_failed,
    run_environment_check,
    write_run_summary,
)

DAG_ID = "careflow_daily_analytics"

# Daily at 02:00 -- after the prior day's data is expected to have
# settled, well before typical business-hours reporting use.
SCHEDULE = "0 2 * * *"

DEFAULT_ARGS = {
    "owner": "careflow-data-engineering",
    "retries": 1,
    "retry_delay": timedelta(minutes=2),
    "execution_timeout": timedelta(minutes=15),
    "on_failure_callback": task_failure_callback,
    "on_retry_callback": task_retry_callback,
    "on_success_callback": task_success_callback,
}


def _environment_check(**context):
    # generate_data is never true on the daily DAG -- Java/Git checks
    # are skipped, matching "does not regenerate Synthea data by default".
    return run_environment_check({"generate_data": False})


def _final_summary(**context):
    dag_run = context["dag_run"]
    task_instances = [
        {"task_id": ti.task_id, "state": ti.state, "duration": ti.duration, "try_number": ti.try_number}
        for ti in dag_run.get_task_instances()
        if ti.task_id != "final_summary"
    ]
    summary = build_run_summary(
        dag_id=DAG_ID,
        run_id=dag_run.run_id,
        started_at=str(dag_run.start_date),
        completed_at=str(datetime.utcnow()),
        task_instances=task_instances,
        conf={},
    )
    reports_dir = get_project_root() / "reports" / "airflow"
    written = write_run_summary(summary, reports_dir)
    raise_if_run_failed(summary)  # keeps the DAG run's own state accurate -- see docstring
    return {
        "final_status": summary["final_status"],
        "failed_tasks": summary["failed_tasks"],
        "report_paths": {k: str(v) for k, v in written.items()},
    }


with DAG(
    dag_id=DAG_ID,
    description="Incremental daily run: profile -> validate -> Bronze -> Silver -> Gold -> PostgreSQL -> dbt build",
    schedule=SCHEDULE,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["careflow", "healthcare", "data-engineering", "daily"],
    default_args=DEFAULT_ARGS,
    on_success_callback=dag_success_callback,
    on_failure_callback=dag_failure_callback,
) as dag:

    environment_check = PythonOperator(
        task_id="environment_check",
        python_callable=_environment_check,
    )

    profile_raw_data = CareFlowCommandOperator(
        task_id="profile_raw_data",
        command_key="profile_raw_data",
    )

    validate_raw_data = CareFlowCommandOperator(
        task_id="validate_raw_data",
        command_key="validate_raw_data",
    )

    ingest_bronze_incremental = CareFlowCommandOperator(
        task_id="ingest_bronze_incremental",
        command_key="ingest_bronze",
    )

    build_silver_incremental = CareFlowCommandOperator(
        task_id="build_silver_incremental",
        command_key="build_silver",  # no --force: relies on Bronze-checksum-based skip
    )

    build_gold_incremental = CareFlowCommandOperator(
        task_id="build_gold_incremental",
        command_key="build_gold",  # no --force: relies on dependency-signature-based skip
    )

    ensure_postgres_ready = CareFlowCommandOperator(
        task_id="ensure_postgres_ready",
        command_key="start_postgres",
        retries=3,
        retry_delay=timedelta(seconds=30),
        execution_timeout=timedelta(minutes=5),
    )

    load_postgres_incremental = CareFlowCommandOperator(
        task_id="load_postgres_incremental",
        command_key="load_postgres_warehouse",  # no --force: checksum-based skip preserved
    )

    validate_postgres = CareFlowCommandOperator(
        task_id="validate_postgres",
        command_key="validate_postgres_warehouse",
    )

    dbt_build = CareFlowCommandOperator(
        task_id="dbt_build",
        command_key="run_dbt_build",
        retries=1,
        execution_timeout=timedelta(minutes=20),
    )

    final_summary = PythonOperator(
        task_id="final_summary",
        python_callable=_final_summary,
        trigger_rule=TriggerRule.ALL_DONE,
    )

    (
        environment_check
        >> profile_raw_data
        >> validate_raw_data
        >> ingest_bronze_incremental
        >> build_silver_incremental
        >> build_gold_incremental
        >> ensure_postgres_ready
        >> load_postgres_incremental
        >> validate_postgres
        >> dbt_build
        >> final_summary
    )
